### ISSUE TITLE
Setting to disable/enable extra information for the device name

### ISSUE THREAD

**Issue by psycoticninja** [grzegorz914/homebridge-meraki-control#14]
By default when adding the WiFi SSIDs and switch interfaces to Homebridge, it also adds to the beginning some extra characters to it, eg.

W. SSID 1 (WiFi) or 1. Interface 1, 2. Interface 2 etc. (for switch interface name)

This is easy to modify when added initially in the Home app, but if Homebridge has a problem or reset of the bridge is needed it looks like it reverts back to displaying the beginning characters.

Is it possible to add some control to enable/disable the extra characters?

**Comment by grzegorz914** [comment]
This is possible but is added intentionally to identify switch port and wireless SSID.
I can add this in next update to plugin config.

**Comment by grzegorz914** [comment]
added in 0.17.0

**Comment by psycoticninja** [comment]
I have updated, but this is working for SSIDs, but not for switches.
Could you double check?

**Comment by grzegorz914** [comment]
fixed
